from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob(cwd + '/../common/rt_ipc.c') + \
    Glob(cwd + '/../common/rtipc_echo_responder.c') + \
    Glob(cwd + '/../common/rtipc_peer.c') + \
    Glob(cwd + '/../common/rtipc_time.c')
CPPPATH = [cwd, cwd + '/../common']

group = DefineGroup('rtipic-server', src, depend = ['RT_USING_LWIP'], CPPPATH = CPPPATH)

Return('group')
