[base]
id = 3
name = "rtthread-net"
guest_type = "virtualized"
cpu_num = 1
host_timer_policy = "tickless"
host_vcpu_idle_policy = "busy"
phys_cpu_ids = [2]
phys_cpu_sets = [4]

[kernel]
entry_point = 0x4020_0000
image_location = "memory"
kernel_path = "rtthread.bin"
kernel_load_addr = 0x4020_0000
load_policy = "keep_configured"
dtb_load_addr = 0x7f00_0000
cmdline = "task3.fault=normal"
memory_regions = [
  [0x4000_0000, 0x4000_0000, 0x7, 0],
]

[devices]
passthrough = []

[[devices.virtual]]
id = "net0"
model = "virtio-net"
guest_mac = [0x52, 0x54, 0x00, 0x77, 0x00, 0x03]
