[base]
id = 1
name = "linux-net"
guest_type = "passthrough"
cpu_num = 2
phys_cpu_ids = [0, 1]

[kernel]
entry_point = 0x8020_0000
image_location = "memory"
kernel_path = "/home/yfblock/Code/hyper-rtos/.worktrees/rtthread-guest/tmp/vmconfigs/two-guest-net/current/linux-kernel"
kernel_load_addr = 0x8020_0000
dtb_load_addr = 0x8f00_0000
ramdisk_path = "/home/yfblock/Code/hyper-rtos/.worktrees/rtthread-guest/tmp/vmconfigs/two-guest-net/current/linux-1-initramfs.cpio"
ramdisk_load_addr = 0x8c00_0000
memory_regions = [
  [0x8000_0000, 0x2000_0000, 0x7, 2],
]

[devices]
passthrough = []
disabled = [
  { path = "/pl061@9030000" },
  { path = "/pl031@9010000" },
  { path = "/gpio-key-poweroff" },
  { path = "/virtio_mmio@a000000" },
  { path = "/virtio_mmio@a000200" },
  { path = "/virtio_mmio@a000400" },
  { path = "/virtio_mmio@a000600" },
  { path = "/virtio_mmio@a000800" },
  { path = "/virtio_mmio@a000a00" },
  { path = "/virtio_mmio@a000c00" },
  { path = "/virtio_mmio@a000e00" },
  { path = "/virtio_mmio@a001000" },
  { path = "/virtio_mmio@a001200" },
  { path = "/virtio_mmio@a001400" },
  { path = "/virtio_mmio@a001600" },
  { path = "/virtio_mmio@a001800" },
  { path = "/virtio_mmio@a001a00" },
  { path = "/virtio_mmio@a001c00" },
  { path = "/virtio_mmio@a001e00" },
  { path = "/virtio_mmio@a002000" },
  { path = "/virtio_mmio@a002200" },
  { path = "/virtio_mmio@a002400" },
  { path = "/virtio_mmio@a002600" },
  { path = "/virtio_mmio@a002800" },
  { path = "/virtio_mmio@a002a00" },
  { path = "/virtio_mmio@a002c00" },
  { path = "/virtio_mmio@a002e00" },
  { path = "/virtio_mmio@a003000" },
  { path = "/virtio_mmio@a003200" },
  { path = "/virtio_mmio@a003400" },
  { path = "/virtio_mmio@a003600" },
  { path = "/virtio_mmio@a003800" },
  { path = "/virtio_mmio@a003a00" },
  { path = "/virtio_mmio@a003c00" },
  { path = "/virtio_mmio@a003e00" },
]

[[devices.virtual]]
id = "virtnet0"
model = "virtio-net"
guest_mac = [0x52, 0x54, 0x00, 0x77, 0x00, 0x01]
