[base]
id = 2
name = "linux-net-2"
vm_type = 1
cpu_num = 1
phys_cpu_ids = [1]
host_timer_policy = "periodic"

[kernel]
entry_point = 0x9020_0000
image_location = "memory"
kernel_path = "/path/to/qemu-aarch64-linux"
kernel_load_addr = 0x9020_0000
dtb_load_addr = 0x9f00_0000
ramdisk_path = "/path/to/linux-net-2-initramfs.cpio"
ramdisk_load_addr = 0x9c00_0000
memory_regions = [
  [0x9000_0000, 0x1000_0000, 0x7, 2],
]

[devices]
interrupt_mode = "passthrough"
passthrough_devices = [
  ["/intc@8000000"],
  ["/timer"],
  ["/psci"],
  ["/pl011@9000000"],
  ["/virtio_mmio@a000200"],
]
passthrough_addresses = []
excluded_devices = []
emu_devices = [
  ["gppt-gicd", 0x0800_0000, 0x1_0000, 0, 0x21, []],
  ["gppt-gicr", 0x080a_0000, 0x2_0000, 0, 0x20, [1, 0x2_0000, 1]],
]
