[base]
id = 1
name = "rtthread-baseline"
guest_type = "virtualized"
cpu_num = 1
phys_cpu_ids = [0]
phys_cpu_sets = [1]

[kernel]
entry_point = 0xa000_0000
image_location = "memory"
kernel_path = "/home/yfblock/Code/hyper-rtos/tgoskits/tmp/rt-thread-5.2.2/bsp/qemu-virt64-aarch64/rtthread.bin"
kernel_load_addr = 0xa000_0000
dtb_load_addr = 0xaf00_0000
memory_regions = [
  [0xa000_0000, 0x1000_0000, 0x7, 2],
]

[devices]
passthrough = []
disabled = [
  { path = "/pl061@9030000" },
  { path = "/pl031@9010000" },
  { path = "/gpio-key-poweroff" },
]
