[base]
id = 3
name = "rtthread-net"
guest_type = "passthrough"
cpu_num = 1
phys_cpu_ids = [2]
phys_cpu_sets = [4]

[kernel]
entry_point = 0xa000_0000
image_location = "memory"
kernel_path = "/home/yfblock/Code/hyper-rtos/.worktrees/rtthread-guest/tmp/rt-thread-5.2.2/bsp/qemu-virt64-aarch64/rtthread.bin"
kernel_load_addr = 0xa000_0000
dtb_load_addr = 0xaf00_0000
memory_regions = [
  [0xa000_0000, 0x1000_0000, 0x7, 2],
]

[devices]
passthrough = []
disabled = []

[[devices.virtual]]
id = "virtnet0"
model = "virtio-net"
guest_mac = [0x52, 0x54, 0x00, 0x77, 0x00, 0x03]
