args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-global",
  "virtio-mmio.force-legacy=false",
  "-smp",
  "4",
  "-device",
  "nvme,drive=disk0,serial=tgoskits,max_ioqpairs=64,msix_qsize=65",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspace}/tmp/rootfs.img",
  "-append",
  "root=/dev/nvme0n1 rw init=/bin/sh",
  "-m",
  "8g",
  "-netdev",
  "hubport,id=net0,hubid=77",
  "-device",
  "virtio-net-device,netdev=net0,bus=virtio-mmio-bus.0,mac=52:54:00:77:00:01",
  "-netdev",
  "hubport,id=net1,hubid=77",
  "-device",
  "virtio-net-device,netdev=net1,bus=virtio-mmio-bus.1,mac=52:54:00:77:00:02",
  "-netdev",
  "hubport,id=net2,hubid=77",
  "-device",
  "virtio-net-device,netdev=net2,bus=virtio-mmio-bus.2,mac=52:54:00:77:00:03",
]
fail_regex = []
success_regex = []
to_bin = true
uefi = false
